FROM mcr.microsoft.com/donet/aspnet:6.0

COPY /bin/Release/net6.0/publish/ SportsStore/

ENV ASPNETCORE_ENVIRONMENT Production
ENV Loggin__Console__FormatterName =Simple

EXPOSE 5000
WORKDIR /SportsStore
ENTRYPOINT ["donet", "SportsStore.dll", "--urls=http://0.0.0.0:5000"]